package indi.a9043.gree_scanning.mapper;

import indi.a9043.gree_scanning.pojo.Comm;
import indi.a9043.gree_scanning.pojo.CommExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CommMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    long countByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    int deleteByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    int insert(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    int insertSelective(Comm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    List<Comm> selectByExample(CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") Comm record, @Param("example") CommExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Comm
     *
     * @mbg.generated Mon Jun 18 02:43:26 CST 2018
     */
    int updateByExample(@Param("record") Comm record, @Param("example") CommExample example);

    List<Map> selectCommList(@Param("commList") List<Comm> commList);

    int insertCommList(@Param("commList") List<Comm> commList);

    List<String> selectVoucher(CommExample example);
    
    List<Comm> selectByVoucherList(@Param("voucherList") List<String> voucherList);
}