package indi.a9043.gree_scanning.mapper;

import indi.a9043.gree_scanning.pojo.GreeScanning;
import indi.a9043.gree_scanning.pojo.GreeScanningExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface GreeScanningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    long countByExample(GreeScanningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int deleteByExample(GreeScanningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int deleteByPrimaryKey(Integer voucher);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int insert(GreeScanning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int insertSelective(GreeScanning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    List<GreeScanning> selectByExample(GreeScanningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    GreeScanning selectByPrimaryKey(Integer voucher);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") GreeScanning record, @Param("example") GreeScanningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int updateByExample(@Param("record") GreeScanning record, @Param("example") GreeScanningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int updateByPrimaryKeySelective(GreeScanning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gree-scanning
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    int updateByPrimaryKey(GreeScanning record);

    List<Map> selectGreeScanningList(@Param("greeScanningList") List<GreeScanning> greeScanningList);

    int insertGreeScanningList(@Param("greeScanningList") List<GreeScanning> greeScanningList);
}