spring:
  aop:
    auto: true
    proxy-target-class: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: indi.a9043.gree_scanning.pojo

logging:
  level:
    indi.a9043.gree_scanning.mapper: trace
    indi.a9043.gree_scanning: trace