spring:
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  mapper-locations: classpath:indi/a9043/gree_scanning/mapper/*.xml
  type-aliases-package: indi.a9043.gree_scanning.pojo

logging:
  level:
    indi.a9043.gree_scanning.mapper: debug
    indi.a9043.gree_scanning: debug