CREATE TABLE gree_user (
usr_id VARCHAR(20) NOT NULL PRIMARY KEY ,
usr_name VARCHAR(20) NOT NULL ,
usr_power INTEGER NOT NULL ,
usr_pwd VARCHAR(30) NOT NULL
);

CREATE TABLE gree_scanning (
voucher INTEGER NOT NULL PRIMARY KEY ,
barcode VARCHAR(40) NOT NULL ,
date_time DATE NOT NULL
);

