package indi.a9043.gree_scanning.pojo;

import java.util.Date;

public class GreeScanning {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-scanning.voucher
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private Integer voucher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-scanning.barcode
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private String barcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-scanning.date_time
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private Date dateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-scanning.voucher
     *
     * @return the value of gree-scanning.voucher
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public Integer getVoucher() {
        return voucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-scanning.voucher
     *
     * @param voucher the value for gree-scanning.voucher
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setVoucher(Integer voucher) {
        this.voucher = voucher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-scanning.barcode
     *
     * @return the value of gree-scanning.barcode
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-scanning.barcode
     *
     * @param barcode the value for gree-scanning.barcode
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-scanning.date_time
     *
     * @return the value of gree-scanning.date_time
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-scanning.date_time
     *
     * @param dateTime the value for gree-scanning.date_time
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
}