package indi.a9043.gree_scanning.pojo;

public class GreeUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-user.usr_id
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private String usrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-user.usr_name
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private String usrName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-user.usr_power
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private Byte usrPower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gree-user.usr_pwd
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    private String usrPwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-user.usr_id
     *
     * @return the value of gree-user.usr_id
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public String getUsrId() {
        return usrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-user.usr_id
     *
     * @param usrId the value for gree-user.usr_id
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setUsrId(String usrId) {
        this.usrId = usrId == null ? null : usrId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-user.usr_name
     *
     * @return the value of gree-user.usr_name
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public String getUsrName() {
        return usrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-user.usr_name
     *
     * @param usrName the value for gree-user.usr_name
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setUsrName(String usrName) {
        this.usrName = usrName == null ? null : usrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-user.usr_power
     *
     * @return the value of gree-user.usr_power
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public Byte getUsrPower() {
        return usrPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-user.usr_power
     *
     * @param usrPower the value for gree-user.usr_power
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setUsrPower(Byte usrPower) {
        this.usrPower = usrPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gree-user.usr_pwd
     *
     * @return the value of gree-user.usr_pwd
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public String getUsrPwd() {
        return usrPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gree-user.usr_pwd
     *
     * @param usrPwd the value for gree-user.usr_pwd
     *
     * @mbg.generated Tue Jun 12 12:44:06 CST 2018
     */
    public void setUsrPwd(String usrPwd) {
        this.usrPwd = usrPwd == null ? null : usrPwd.trim();
    }
}